import {escapeHtml,safeClass} from './utils.js';
import {apiFetch} from './api.js';

function alertRowHTML(alert,{variant='row',resolveButton=false,arrow=false}={}){const compact=variant==='notification';const icon=compact?`notification-icon ${safeClass(alert.severity,['critical','warning','info'],'info')}`:`alert-symbol ${alert.severity==='critical'?'critical-symbol':'warning-symbol'}`;const meta=compact?escapeHtml(new Date(alert.created_at).toLocaleString()):`${escapeHtml(alert.severity)} · ${escapeHtml(new Date(alert.created_at).toLocaleString())}${alert.active?'':' · resolved'}`;return `<div class="${compact?'notification-item':'alert-row'}"><span class="${icon}">!</span><div><b>${escapeHtml(alert.device_name||'Network device')}</b><p>${escapeHtml(alert.message)}</p><small>${meta}</small></div>${resolveButton&&alert.active?`<button class="btn btn-secondary resolve-alert" data-alert-id="${escapeHtml(alert.id)}">Resolve</button>`:arrow?'<span class="alert-arrow">›</span>':''}</div>`}
async function loadDashboardAlerts(){const list=document.getElementById('dashboardAlertList');if(!list)return;try{const alerts=await apiFetch('/api/alerts');const active=alerts.filter(alert=>alert.active!==0).slice(0,3);list.innerHTML=active.length?active.map(alert=>alertRowHTML(alert,{arrow:true})).join(''):'<p class="notification-empty">No active alerts</p>'}catch(error){list.innerHTML=`<p class="notification-empty">${escapeHtml(error.message)}</p>`}}
async function renderAlerts(){const panel=document.getElementById('alertsViewPanel');if(!panel)return;try{const alerts=await apiFetch('/api/alerts');panel.innerHTML=alerts.length?alerts.map(alert=>alertRowHTML(alert,{resolveButton:true})).join(''):'<p class="notification-empty">No alerts recorded</p>'}catch(error){panel.innerHTML=`<p class="notification-empty">${escapeHtml(error.message)}</p>`}}
const notificationsBtn=document.getElementById('notificationsBtn');const notificationPopover=document.getElementById('notificationPopover');const notificationBody=document.getElementById('notificationBody');
async function loadNotifications(){try{const alerts=await apiFetch('/api/alerts');const activeAlerts=alerts.filter(alert=>alert.active!==0);notificationBody.innerHTML=activeAlerts.length?activeAlerts.slice(0,8).map(alert=>alertRowHTML(alert,{variant:'notification'})).join(''):'<p class="notification-empty">No active alerts</p>';}catch(error){notificationBody.innerHTML=`<p class="notification-empty">${escapeHtml(error.message)}</p>`}}
notificationsBtn.addEventListener('click',()=>{notificationPopover.hidden=!notificationPopover.hidden;if(!notificationPopover.hidden)loadNotifications()});
document.getElementById('closeNotifications').addEventListener('click',()=>notificationPopover.hidden=true);
document.getElementById('viewNotifications').addEventListener('click',()=>{notificationPopover.hidden=true;document.querySelector('[data-view="alerts"]').click()});
document.addEventListener('click',event=>{if(!event.target.closest('.notification-wrap'))notificationPopover.hidden=true});
export {alertRowHTML,loadDashboardAlerts,renderAlerts,loadNotifications};
