import {escapeHtml,safeClass,deviceStatus} from './utils.js';
import {apiFetch} from './api.js';
import {showToast} from './toast.js';
import {loadDevicesFromApi} from './devices.js';

let mapNodes=[];let monitoredDevices=[];let currentMapId=null;
async function saveMapNodes(){if(!currentMapId)return;try{await apiFetch(`/api/maps/${currentMapId}/layout`,{method:'PUT',body:JSON.stringify({nodes:mapNodes.filter(node=>node.deviceId).map(node=>({device_id:node.deviceId,x:node.x,y:node.y}))})})}catch(error){console.warn('Map layout save failed',error)}}
async function loadMaps(){const maps=await apiFetch('/api/maps');if(!currentMapId||!maps.some(map=>map.id===currentMapId))currentMapId=maps[0]?.id;const selector=document.getElementById('mapSelector');if(selector){selector.innerHTML=maps.map(map=>`<option value="${escapeHtml(map.id)}">${escapeHtml(map.name)} (${escapeHtml(map.device_count)})</option>`).join('');selector.value=String(currentMapId||'')}}
async function loadMapDevices(){
  try{await loadMaps();const [list,topology]=await Promise.all([apiFetch('/api/devices'),apiFetch(`/api/maps/${currentMapId}/topology`)]);monitoredDevices=list;const positions=new Map(topology.map(node=>[node.device_id,node]));mapNodes=topology.map((device,index)=>{const saved=positions.get(device.device_id);return {id:`device-${device.device_id}`,deviceId:device.device_id,name:device.name,host:device.host,status:deviceStatus(device),x:saved?.x??18+(index%3)*30,y:saved?.y??25+Math.floor(index/3)*28}});renderMap()}catch(error){console.warn('Map devices load failed',error)}}
async function createMap(){const name=prompt('ชื่อไซต์งานหรือแผนผังใหม่');if(!name?.trim())return;const description=prompt('รายละเอียดไซต์งาน (ถ้ามี)')||'';try{const result=await apiFetch('/api/maps',{method:'POST',body:JSON.stringify({name:name.trim(),description})});currentMapId=result.id;await loadMapDevices();showToast('Map created',result.name)}catch(error){showToast('Unable to create map',error.message)}}
function renderMap(){
  const canvas=document.getElementById('mapCanvas');if(!canvas)return;
  canvas.querySelectorAll('.map-editor-node').forEach(node=>node.remove());
  const empty=document.getElementById('mapEmpty');if(empty)empty.style.display=mapNodes.length?'none':'block';
  mapNodes.forEach(node=>{const element=document.createElement('div');element.className=`map-editor-node ${safeClass(node.status,['online','warning','critical'],'online')}`;element.dataset.nodeId=node.id;element.style.left=`${node.x}%`;element.style.top=`${node.y}%`;element.innerHTML=`<div class="map-node-content"><b>${escapeHtml(node.name)}</b><span>${escapeHtml(node.host)} · ${escapeHtml(node.status)}</span></div><div class="map-node-actions"><button data-map-action="edit" title="Edit node">✎</button><button data-map-action="delete" title="Delete node">×</button></div>`;canvas.appendChild(element);element.querySelector('[data-map-action="edit"]').addEventListener('click',()=>editMapNode(node));element.querySelector('[data-map-action="delete"]').addEventListener('click',()=>deleteMapNode(node));makeNodeDraggable(element,node)});
}
function makeNodeDraggable(element,node){let dragging=false,offsetX=0,offsetY=0;element.addEventListener('pointerdown',event=>{if(event.target.closest('button'))return;dragging=true;element.setPointerCapture(event.pointerId);const rect=element.getBoundingClientRect();offsetX=event.clientX-rect.left;offsetY=event.clientY-rect.top;element.classList.add('dragging')});element.addEventListener('pointermove',event=>{if(!dragging)return;const rect=document.getElementById('mapCanvas').getBoundingClientRect();node.x=Math.max(2,Math.min(88,((event.clientX-rect.left-offsetX)/rect.width)*100));node.y=Math.max(4,Math.min(82,((event.clientY-rect.top-offsetY)/rect.height)*100));element.style.left=`${node.x}%`;element.style.top=`${node.y}%`});element.addEventListener('pointerup',()=>{if(!dragging)return;dragging=false;element.classList.remove('dragging');saveMapNodes()})}
function addMapNode(){if(!monitoredDevices.length){showToast('No devices available','Add a device from the Devices page first');return}const options=monitoredDevices.map((device,index)=>`${index+1}. ${device.name} (${device.host})`).join('\n');const selected=Number(prompt(`เลือกอุปกรณ์จากระบบที่ต้องการเพิ่ม:\n${options}\n\nใส่หมายเลขอุปกรณ์`));const device=monitoredDevices[selected-1];if(!device)return;if(mapNodes.some(node=>node.deviceId===device.id)){showToast('Device already on map','This device is already displayed');return}mapNodes.push({id:`device-${device.id}`,deviceId:device.id,name:device.name,host:device.host,status:deviceStatus(device),x:35+Math.random()*25,y:35+Math.random()*25});saveMapNodes();renderMap()}
async function editMapNode(node){const name=prompt('แก้ไขชื่ออุปกรณ์',node.name);if(name===null||!name.trim())return;const host=prompt('แก้ไข IP address หรือ URL',node.host);if(host===null||!host.trim())return;try{const result=await apiFetch(`/api/devices/${node.deviceId}`,{method:'PUT',body:JSON.stringify({name:name.trim(),host:host.trim()})});Object.assign(node,{name:result.name,host:result.host});await loadDevicesFromApi();renderMap();showToast('Device updated','The device and map were updated')}catch(error){showToast('Unable to update device',error.message)}}
async function deleteMapNode(node){if(!confirm(`ลบ ${node.name} ออกจากแผนผังหรือไม่?`))return;try{await apiFetch(`/api/maps/${currentMapId}/nodes/${node.deviceId}`,{method:'DELETE'});mapNodes=mapNodes.filter(item=>item.id!==node.id);renderMap();await loadMaps();showToast('Node removed','The topology change was saved')}catch(error){showToast('Unable to remove node',error.message)}}
function resetMapLayout(){mapNodes.forEach((node,index)=>{node.x=index%2?65:20;node.y=18+Math.floor(index/2)*28});saveMapNodes();renderMap()}
function onMapSelectorChange(event){currentMapId=Number(event.target.value);loadMapDevices()}
export {renderMap,loadMapDevices,createMap,addMapNode,resetMapLayout,onMapSelectorChange,currentMapId};
