import {apiFetch} from './api.js';
import {showToast} from './toast.js';
import {renderAlerts,loadNotifications} from './alerts.js';
import {checkDevice} from './devices.js';

async function loadThresholds(){const form=document.getElementById('thresholdForm');if(!form)return;try{const values=await apiFetch('/api/settings/thresholds');Object.entries(values).forEach(([key,value])=>{const input=form.elements[key];if(input)input.value=value})}catch(error){showToast('Unable to load thresholds',error.message)}}
function bindSettingsHandlers(secondaryView){
  secondaryView.addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.target);try{let endpoint,payload;if(event.target.id==='smtpForm'){endpoint='/api/settings/notifications';payload={smtp_host:form.get('smtpHost'),smtp_port:Number(form.get('smtpPort')||587),smtp_username:form.get('smtpUser'),smtp_password:form.get('smtpPassword'),smtp_from:form.get('fromAddress'),recipients:[form.get('recipient')].filter(Boolean)}}else if(event.target.id==='thresholdForm'){endpoint='/api/settings/thresholds';payload={cpu_percent:Number(form.get('cpu_percent')),memory_percent:Number(form.get('memory_percent')),disk_percent:Number(form.get('disk_percent')),ssl_days:Number(form.get('ssl_days')),response_ms:2000}}else{return}await apiFetch(endpoint,{method:'PUT',body:JSON.stringify(payload)});showToast(event.target.id==='thresholdForm'?'Thresholds saved':'SMTP settings saved','Monitoring settings updated')}catch(error){showToast('Settings save failed',error.message)}});
  secondaryView.addEventListener('click',async event=>{const deviceButton=event.target.closest('.device-check');if(deviceButton){checkDevice(Number(deviceButton.dataset.deviceId),deviceButton);return}if(event.target.id==='testEmailBtn'){try{await apiFetch('/api/settings/notifications/test',{method:'POST'});showToast('Test email sent','Check the configured recipient inbox')}catch(error){showToast('Test email failed',error.message)}}if(event.target.id==='saveSettingsBtn')showToast('Settings saved','Monitoring preferences updated');const resolveButton=event.target.closest('.resolve-alert');if(resolveButton){try{await apiFetch(`/api/alerts/${resolveButton.dataset.alertId}/resolve`,{method:'POST'});await renderAlerts();loadNotifications();showToast('Alert resolved','The alert is no longer active')}catch(error){showToast('Unable to resolve alert',error.message)}}});
}
export {loadThresholds,bindSettingsHandlers};
